{% set name = "csdms-sedflux-3d" %}
{% set version = "3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/mcflugen/sedflux
  git_branch: add-function-pointers

requirements:
  build:
    - babelizer
    - sedflux
    - landlab
  run:
    - cca-babel <2
    - cca-spec-babel
    - ccaffeine
    - sedflux
    - landlab

test:
  requires:
    - pymt

build:
  number: 4
  tracks: cb14

about:
  home: https://github.com/mcflugen/sedflux
  license: MIT
  summary: 3D sedflux
  doc_url: http://sedflux.readthedocs.io/
  dev_url: http://github.com/mcflugen/sedflux
