language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: iu2eu7mZLlGatc3X1wzWnQazF4Ejt8vo+18Y01anG9O6TkgnlY0uUvz3bWhjneUkk0qZN4a8/RmEzDNiIW4hzdS/BoF7pRZj/BCl27FaS7Z0D5O5kxdQen6i1V+Fo9/asPibDBU7qh3nk19c1WUnDliRokNIzsnDOQQx24pXhlZOvJfSEZiHmH9dbQ6I8Iad1C+qJgd4hR2/LdvlC+NMlAPdfP/x4iti3hQDhFcqCQFDfGDOFRdAW0OahLWDhgvzSppiKsf92vIbRBaGLul4hv2F4XNxjsaeBiWX55B4uM3dgKHvv0G3B9sho1aqppSTKoUKhBVqlY/RUI+3e+J9omrCUfL9/YcGj3DKnze2rOT9YlAO0oUsOwxvW6Z1p+8z7cNZlTfbGkYwnP4ee6U1I0zW6EW4eybr/6S1jdtX8gfdYPzp+X9RwzNvwBs2O3AN6ztTsi29Dg9/bWxKjS/GYL1kbJAzPvR8FQeZRQEX/dD3ntFzLiZZaTuoRvg3oZU3sAmcnbtzWreIz+OybQgHpRykOgK6SE3l5WOuBekwwSBchYRU7wtGQ7EHMzrkLUJ31aTxfA8y8oNpVUUxSu7FCrHoP0hruWfjlATOqTX79OZOE/V+JC2hM5Z7MVmArQcNmDqmUbeQtq6VRsyuxRTWLwNkCBL1Cmf+imrPhbNt77U=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- travis_wait 40 conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
