language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: "FhcfBPEVbSYv83IPEXoy8g2QJFI52G44htb22RvOc3TZuhfHXAJXof8nM7Yv4ot/fEtwehpn0xP30653ekFs1zsoZumP++05MpuoZwPaZGgYR8BBnV6JEwof9W7pjhE1M0/k0aJUq0xLGOgfXhg0ACf1zpvj5lRdS2NsBZKfC2lpbf2u3eXGQ5+rXAjfFxwT+ZOt0NwG52j+oaAfDOx5CE9I+Xe+5vdNned0oPnPR3VExB9crqughGdKYPPss0ElXU6jgKx0+4/G61DRKBQhuNSkewiP6XWp7dcVxcXGM3xOpPBa66+UFtSiTfGHq3astGjyJF12mLY3pzWA6YKqTWJvxGXUXqHyER3HO+zxDX5bFUbMfaA8dKjhOc3nqUw9FqKD+GlZByctO/mLEbqIcn3EDO7M53VcSvLIQ6sDH4na9FjNhg8sKfdFK0Zp5LK9kjjqu5Se954soJKIl54CTMeWn9yYXub2Nw0JBuuQaP3F4ufDlGlKmGYl/dxos4s4dZvVzrRIhp2YX2OGgg60GhK+fq7XtevJjqyTyTdhSvFgJp56MGZW4p+28IPEDmkeZ8o/vayPYXBMaAR2b0qxgmoXFghi9qnRXHU3twwlngZqcGZ0ROlI5CAFrP4wzb8E0xygeiAXzfucmW5cgGD9dozyeQzXlB7MLUHm5iQjnEI="
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- travis_wait 40 conda build ./recipe -c csdms-stack -c defaults -c conda-forge --old-build-string
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --old-build-string --token=-
